
frase= 'curso em video python'
print(frase)
print(frase[3])
print(frase[3:13])
print(frase[3:13:2])
print(frase[:3])
print(frase[2:])
print(frase[2::2])
print(frase.count('o'))
print(frase.capitalize())
print(frase.title())
print(frase.lower())
print(frase.upper())
print(frase.replace('python', 'android'))
print(frase.find('video'))
print('video' in frase)
print(frase.split())
dibidido=frase.split()
print(dibidido[3])
print((dibidido[3][2]))